// 각 과별 중단원 파일명과 제목
$tl = array(
array("r0-Alphabet"=>"A. Alphabet","r0-Quizzzz"=>"B. Quiz","r0-Zuordnung"=>"C. Zuordnung"),
array("r1-Guten Tag!"=> "A. Guten Tag!","r1-Wie heissen Sie"=>"B. Wie heißen Sie?","r1-Wie geht es Ihnen"=>"C. Wie geht es Ihnen?","r1-Wer ist Hyun Kim"=>"D. Wer ist Hyun Kim?","r1-Zahlen(1-10)"=>"F. Zahlen(1~10)","r1-Uebungen"=>"G. Übungen","r1-Grammatik und Wendungen"=>"H. Grammatik und Wendungen"),
array("r2-Woher kommen Sie!"=>"A. Woher kommen Sie?","r2-Ich bin Koreanerin"=>"B. Ich bin Koreanerin.","r2-Welche Sprachen sprechen Sie"=>"C. Welche Sprachen sprechen Sie?","r2-Wo liegt das Land"=>"D. Wo liegt das Land?","r2-Uebungen"=>"E. Übungen","r2-Grammatik und Wendungen"=>"F. Grammatik und Wendungen"),
array("r3-Wer ist das"=>"A. Wer ist das?","r3-Wie alt ist er"=>"B. Wie alt ist er?","r3-Wie viele Geschwister hast du"=>"C. Wie viele Geschwister hast du?","r3-Was sind Sie von Beruf"=>"D. Was sind Sie von Beruf?","r3-Visitenkarten"=>"E. Visitenkarten","r3-Uebungen"=>"F. Übungen","r3-Grammatik und Wendungen"=>"G. Grammatik und Wendungen"),
array("r4-Wohnen"=>"A. Wohnen","r4-Im Zimmer"=>"B. Im Zimmer","r4-Was ist das"=>"C. Was ist das?","r4-Wie ist das"=>"D. Wie ist das?","r4-Uebungen"=>"E. Übungen","r4-Grammatik und Wendungen"=>"F. Grammatik und Wendungen"),
array("r5-Essen und Trinken"=>"A. Essen und Trinken","r5-Was isst du gern und was trinkst du gern"=>"B. Was isst du gern und was trinkst du gern?","r5-Was isst und trinkt er,sie"=>"C. Was isst und trinkt er/sie?","r5-Im Restaurant. Was bekommen Sie"=>"D. Im Restaurant. Was bekommen Sie?","r5-Waehrend des Essens"=>"E. Während des Essens","r5-Was bezahlen Sie"=>"F. Was bezahlen Sie?","r5-Uebungen"=>"G. Übungen","r5-Grammatik und Wendungen"=>"H. Grammatik und Wendungen"),
array("r6-Was machst du gern"=>"A. Was machst du gern?","r6-Wie spaet ist es"=>"B. Wie spät ist es?","r6-Wann hast du Deutschunterricht"=>"C. Wann hast du Deutschunterricht?","r6-Tagesablauf"=>"D. Tagesablauf","r6-Uebungen"=>"E. Übungen","r6-Grammatik und Wendungen"=>"F. Grammatik und Wendungen"),
array("r7-Wochenende, Was haben Sie am Wochenende vor"=>"A. Wochenende: Was haben Sie am Wochenende vor?","r7-Verabredung. Hast du heute Abend Zeit"=>"B. Verabredung. Hast du heute Abend Zeit?","r7-Anweisungen"=>"C. Anweisungen: Was kann man, was darf man nicht?","r7-Uebungen"=>"D. Übungen","r7-Grammatik und Wendungen"=>"E. Grammatik und Wendungen"),
array("r8-Koerper und Sport"=>"A. Körper und Sport","r8-Koerperteile und Taetigkeiten"=>"B. Körperteile und Tätigkeiten","r8-Krankheiten und Schmerzen"=>"C. Krankheiten und Schmerzen","r8-Beim Arzt"=>"D. Beim Arzt","r8-Uebungen"=>"E. Übungen","r8-Grammatik und Wendungen"=>"F. Grammatik und Wendungen"),
array("r9-Feste in Deutschland"=>"A. Feste in Deutschland","r9-Geburtstagsfeier"=>"B. Geburtstagsfeier","r9-Geschenke. Wer schenkt wem was"=>"C. Geschenke. Wer schenkt wem was?","r9-Einladungskarte"=>"D. Einladungskarte","r9-Uebungen"=>"E. Übungen","r9-Grammatik und Wendungen"=>"F. Grammatik und Wendungen"),
array("r10-Stadtplan"=>"A. Stadtplan","r10-Nach dem Weg fragen"=>"B. Nach dem Weg fragen","r10-Sehenswuerdigkeiten in Dresden"=>"C. Sehenswürdigkeiten in Dresden","r10-Urlaub in Dresden"=>"D. Urlaub in Dresden","r10-Uebungen"=>"E. Übungen","r10-Grammatik und Wendungen"=>"F. Grammatik und Wendungen")
);

// 각 과별 중단원 파일명과 제목 번역
$tl_k = array(
array("r0-Alphabet"=>"알파벳","r0-Quizzzz"=>"퀴즈","r0-Zuordnung"=>"연결하기"),
array("r1-Guten Tag!"=> "안녕하세요!","r1-Wie heissen Sie"=>"이름이 어떻게 되시나요?","r1-Wie geht es Ihnen"=>"어떻게 지내시나요?","r1-Wer ist Hyun Kim"=>"김현이 누구인가요?","r1-Zahlen(1-10)"=>"수(1~10)","r1-Uebungen"=>"연습하기","r1-Grammatik und Wendungen"=>"문법과 표현"),
array("r2-Woher kommen Sie!"=>"어디서 오셨나요?","r2-Ich bin Koreanerin"=>"저는 한국(여)인입니다.","r2-Welche Sprachen sprechen Sie"=>"어떠한 언어를 말할 수 있나요?","r2-Wo liegt das Land"=>"이 나라는 어디에 있나요?","r2-Uebungen"=>"연습문제","r2-Grammatik und Wendungen"=>"문법과 표현"),
array("r3-Wer ist das"=>"이 분은 누구인가요?","r3-Wie alt ist er"=>"그는 몇 살인가요?","r3-Wie viele Geschwister hast du"=>"형제자매가 몇 명이니?","r3-Was sind Sie von Beruf"=>"직업이 어떻게 되나요?","r3-Visitenkarten"=>"명함","r3-Uebungen"=>"연습문제","r3-Grammatik und Wendungen"=>"문법과 표현"),
array("r4-Wohnen"=>"사는 것","r4-Im Zimmer"=>"방에서","r4-Was ist das"=>"이것은 무엇인가요?","r4-Wie ist das"=>"이것은 어떤가요?","r4-Uebungen"=>"연습문제","r4-Grammatik und Wendungen"=>"문법과 표현"),
array("r5-Essen und Trinken"=>"먹고 마시기","r5-Was isst du gern und was trinkst du gern"=>"무엇을 즐겨 먹고 마셔?","r5-Was isst und trinkt er,sie"=>"그(녀)는 무엇을 먹고 마시나요?","r5-Im Restaurant. Was bekommen Sie"=>"레스토랑에서.<br>무엇을 원하시나요?","r5-Waehrend des Essens"=>"식사 중에","r5-Was bezahlen Sie"=>"무엇을 지불하시겠어요?","r5-Uebungen"=>"연습문제","r5-Grammatik und Wendungen"=>"문법과 표현"),
array("r6-Was machst du gern"=>"하루일과 중 무엇을 즐겨 하니?","r6-Wie spaet ist es"=>"몇시인가요?","r6-Wann hast du Deutschunterricht"=>"독일어 수업이 언제니?","r6-Tagesablauf"=>"하루일과","r6-Uebungen"=>"연습문제","r6-Grammatik und Wendungen"=>"문법과 표현"),
array("r7-Wochenende, Was haben Sie am Wochenende vor"=>"주말: 주말에 무엇을 하나요?","r7-Verabredung. Hast du heute Abend Zeit"=>"약속. 오늘저녁시간있니?","r7-Anweisungen"=>"지시문. 무엇을 할수 있고 해서는 안되나요?","r7-Uebungen"=>"연습문제","r7-Grammatik und Wendungen"=>"문법과 표현"),
array("r8-Koerper und Sport"=>"신체와 스포츠","r8-Koerperteile und Taetigkeiten"=>"신체부위와 하는 일","r8-Krankheiten und Schmerzen"=>"질병과 통증","r8-Beim Arzt"=>"개인병원에서","r8-Uebungen"=>"연습문제","r8-Grammatik und Wendungen"=>"문법과 표현"),
array("r9-Feste in Deutschland"=>"독일의 축제","r9-Geburtstagsfeier"=>"생일파티","r9-Geschenke. Wer schenkt wem was"=>"선물. 누가 누구에게 무엇을 선물하나요?","r9-Einladungskarte"=>"초대장","r9-Uebungen"=>"연습문제","r9-Grammatik und Wendungen"=>"문법과 표현"),
array("r10-Stadtplan"=>"지도","r10-Nach dem Weg fragen"=>"길 묻기","r10-Sehenswuerdigkeiten in Dresden"=>"드레스덴의 명소들","r10-Urlaub in Dresden"=>"드레스덴에서의 휴가","r10-Uebungen"=>"연습문제","r10-Grammatik und Wendungen"=>"문법과 표현")
);
